apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytodo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytodo-backend
  template:
    metadata:
      labels:
        app: pytodo-backend
    spec:
      containers:
      - name: backend
        image: reactacr123456.azurecr.io/pytodo-backend:v1
        ports:
        - containerPort: 8000
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: backend-sql-secret
              key: SQL_SERVER
        - name: SQL_DB
          valueFrom:
            secretKeyRef:
              name: backend-sql-secret
              key: SQL_DB
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: backend-sql-secret
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-sql-secret
              key: SQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: pytodo-backend-svc
spec:
  selector:
    app: pytodo-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
  type: LoadBalancer
